---
title: "Regression"
author: "Lixia"
date: '2022-11-23'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Libraries
library(MASS)
library(ISLR)
```

Simple Linear Regression

```{r}
# View the data
fix(Boston)
names(Boston)
```


```{r}
# Simple Linear Regression
lm.fit=lm(medv~lstat, data=Boston)
lm.fit
summary(lm.fit)
names(lm.fit)
confint(lm.fit)
```


```{r}
# The predict() function can be used to produce confidence intervals and prediction intervals
predict(lm.fit, data.frame(lstat=c(5,10 ,15)), interval ="confidence")
predict(lm.fit, data.frame(lstat=c(5,10 ,15)), interval ="prediction")
```


```{r}
# plot with the least squares regression line
plot(lstat, medv)
abline(lm.fit)

abline(lm.fit, lwd =3)
abline(lm.fit, lwd=3,col ="red")
plot(lstat,medv, col="red")
plot(lstat,medv, pch =20)
plot(lstat,medv, pch ="+")
plot(1:20, 1:20, pch =1:20)
```


```{r}
# split the display screen
par(mfrow=c(2,2))
plot(lm.fit)
plot(predict(lm.fit), residuals(lm.fit))
plot(predict(lm.fit), rstudent(lm.fit))
```

Multiple Linear Regression

```{r}
# Multiple Linear Regression
lm.fit=lm(medv~lstat+age, data=Boston )
summary(lm.fit)
```


```{r}
lm.fit=lm(medv~., data=Boston)
summary(lm.fit)
```


```{r}
lm.fit1=lm(medv~.-age ,data=Boston)
summary(lm.fit1)
```
